### ISSUE TITLE
link to official documentation in the Readme is dead

### ISSUE THREAD

**Issue by erickeller** [jimbo8098/windows-docker-role#7]
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/deploy-containers-on-server points to a 404...
would be good to update it.

**Comment by jimbo8098** [comment]
Interesting! That was correct not that long ago. Will update! Should be https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#prerequisites
